var found = true;
var grade = 88.6;
var firstname = "anne ";
var lastname = "bbacik";
console.log(found);
console.log(" the grade is " + grade);
console.log("burada adiniz var ".concat(firstname, " ve burda ").concat(lastname));
found = false;
grade = 70.1;
firstname = 'degisti';
console.log(found);
console.log(" the grade is " + grade);
console.log("burada adiniz var ".concat(firstname, " ve burda ").concat(lastname));
